### ISSUE TITLE
关于守护进程问题

### ISSUE THREAD

**Issue by JimChenWYU** [huangdijia/laravel-trigger#1]
你好，如果我用 supervisor 守护进程php artisan trigger:start只能设置numprocs=1，因为开启多个进程时会出现重复触发监听的trigger事件

**Comment by huangdijia** [comment]
是的，只能有一个进程，但是消费队列可以多进程

**Comment by JimChenWYU** [comment]
所以如果要通过多进程消费，只能通过trigger时间入队列，通过队列进行多进程消费？

**Comment by huangdijia** [comment]
是的，有兴趣可以交流一下想法

**Comment by JimChenWYU** [comment]
恩，看了一下源码，这个库也只是基于krowinski/php-mysql-replication wrap一层提供laravel接口，无法直接改造成多进程模式，所以我在想能不能把krowinski/php-mysql-replication拿过来直接重写了，也看过它一点源码，它是基于php原生的socket函数实现binlog监听，能不能用swoole把它重写了

**Comment by huangdijia** [comment]
> 恩，看了一下源码，这个库也只是基于krowinski/php-mysql-replication wrap一层提供laravel接口，无法直接改造成多进程模式，所以我在想能不能把krowinski/php-mysql-replication拿过来直接重写了，也看过它一点源码，它是基于php原生的socket函数实现binlog监听，能不能用swoole把它重写了

期待你的作品。
