### ISSUE TITLE
Not an issue - just a question

### ISSUE THREAD

**Issue by cyppe** [huangdijia/laravel-trigger#12]
Hello! 

That is your thoughts about possibility to go back to using krowinski/php-mysql-replication library again instead of the moln/php-mysql-replication fork?

The moln fork works great so no big deal. But it seems like moln is falling behind as krowinski/php-mysql-replication seems to be better maintained last months and also have a few new features like https://github.com/krowinski/php-mysql-replication/pull/112 (rows query event).

I don't know exactly what feature was missing/broken in krowinski's library that made you switch to moln, so before I start looking into it maybe you have some information to share.  Maybe you can easily see if the problems is resolved in the original package now so laravel-trigger could use it again? 

Just afraid moln library might be abandoned as I really love your laravel-trigger package :) 

So please share your thoughts, or if you prefer to stay with Moln that would also be interesting to know. I can probably also help with something if needed.

**Comment by huangdijia** [comment]
https://github.com/krowinski/php-mysql-replication/pull/104/files


Before because symfony dependence conflict, after the official adjustment, you can help mention a PR change back?

**Comment by cyppe** [comment]
Aha got it! 

Yes I can help, but it seems like you were very quick and already tried it?  But I can at least test 6.x branch in my projects and see if it works as expected.

**Comment by huangdijia** [comment]
> Aha got it!
> 
> Yes I can help, but it seems like you were very quick and already tried it? But I can at least test 6.x branch in my projects and see if it works as expected.

👌
