### ISSUE TITLE
Getting unserialized object from cache when using Trigger::getCurrent()

### ISSUE THREAD

**Issue by wize-wiz** [huangdijia/laravel-trigger#5]
I don't know exactly what the status is of this package, but I'm getting a lot of problems configuring the right one. 

I had to install `huangdijia/laravel-trigger` which uses the `"dev-support-laravel10"` to get it installed in the first place using Laravel 9.

Using `huangdijia/laravel-trigger:^4.0` as recommended in the documentation gave me a lot of dependency problems unwillingly to install. That's a topic for a different issue.

After restart `php artisan trigger:start` I'm getting an error stating:

```
  Huangdijia\Trigger\Trigger::getCurrent(): Return value must be of type ?MySQLReplication\BinLog\BinLogCurrent, string returned

  at vendor/huangdijia/laravel-trigger/src/Trigger.php:202
    198▕     public function getCurrent(): ?BinLogCurrent
    199▕     {
    200▕         var_dump(($this->replicationCacheKey));
    201▕         var_dump($this->cache->get($this->replicationCacheKey));
  ➜ 202▕         return with($this->cache->get($this->replicationCacheKey));
    203▕     }
    204▕ 
    205▕     /**
    206▕      * Clear current.
``` 

After inspection, the function `rememberCurrent` seems to serialize the object when storing to cache:

```
    public function rememberCurrent(BinLogCurrent $binLogCurrent): void {
        $this->cache->put($this->replicationCacheKey, serialize($binLogCurrent), Carbon::now()->addHours(1));
    }
```

But `getCurrent` doesn't unserialize the object, although it once did as shown in the changes [here](https://github.com/huangdijia/laravel-trigger/commit/42da3ab894154851d6d38e0c3b6e12ad7d591aaf#diff-6171dd956e44a313075eb0cc423c36e02ecdc078117cefae797800264f1f8eb8).

```
    // current
    public function getCurrent(): ?BinLogCurrent 
    {
        return with($this->cache->get($this->replicationCacheKey));
    }
```

What it used to be
```
    public function getCurrent()
    {
        return with($this->cache->get($this->replicationCacheKey), function ($cache) {
            if (!$cache) {
                return null;
            }

            return unserialize($cache) ?: null;
        });
    }
```

Does `Cache::get` unserialize objects by default I don't know about? Or is there something I'm missing?

I have to add, I'm using redis as cache.

**Comment by huangdijia** [comment]
Please use `^4.0.3`
