### ISSUE TITLE
Cannot install on laravel 10

### ISSUE THREAD

**Issue by cyppe** [huangdijia/laravel-trigger#7]
I get a lot of issues with dependencies when I try to install package on Laravel 10.40.0.

composer require "huangdijia/laravel-trigger:^4.0"

./composer.json has been updated
Running composer update huangdijia/laravel-trigger
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - huangdijia/laravel-trigger v4.1.0 requires moln/php-mysql-replication ^1.2 -> satisfiable by moln/php-mysql-replication[1.2.0, 1.2.1].
    - huangdijia/laravel-trigger[4.0.0, ..., v4.0.3] require illuminate/support ^9.0 -> found illuminate/support[v9.0.0-beta.1, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - moln/php-mysql-replication[1.2.0, ..., 1.2.1] require symfony/event-dispatcher ^3.1|^4.0|^5.0|^6.0 -> found symfony/event-dispatcher[v3.1.0-BETA1, ..., v3.4.47, v4.0.0-BETA1, ..., v4.4.44, v5.0.0-BETA1, ..., v5.4.34, v6.0.0-BETA1, ..., v6.4.2] but the package is fixed to v7.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires huangdijia/laravel-trigger ^4.0 -> satisfiable by huangdijia/laravel-trigger[4.0.0, ..., v4.1.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by huangdijia** [comment]
What version is PHP? I'll try to reproduce it

**Comment by cyppe** [comment]
Hi!

It's php 8.2.13.

But I traced the issue and see that it's due to package moln/php-mysql-replication that has limited the version of  symfony/event-dispatcher to 6.0, when latest laravel uses 7.0.

I added ticket to that package here:  https://github.com/Moln/php-mysql-replication/issues/14

**Comment by cyppe** [comment]
Worst case if the package owner is not active anymore - maybe you can consider to fork moln/php-mysql-replication package and update the dependencies there and use that instead in your composer.json.  At least until they update? 

But hopefully they are still active.

**Comment by huangdijia** [comment]
<img width="339" alt="image" src="https://github.com/huangdijia/laravel-trigger/assets/8337659/50e1e016-fc30-4ae8-b59b-4e7b787ed3a9">

**Comment by cyppe** [comment]
I know, as I understand the moln fork of krowinski/php-mysql-replication added support for Symfony 6. But now we need it bumped again for Symfony 7 version of symfony/event-dispatcher

**Comment by huangdijia** [comment]
Let’s wait for moln to see if it considers supporting symfony 7

**Comment by huangdijia** [comment]
Laravel's version requirement for symfony is 6.x

https://packagist.org/packages/laravel/framework

You check which of your projects depends on which package requires the symfony7.x


run： `composer why symfony/event-dispatcher`

**Comment by cyppe** [comment]
It's actually pretty weird (for me).   My project is a pretty fresh Laravel 10. But probably some library has updated the event-dispatcher to 7.x.  After forking your library + moln/php-mysql-replication and doing some changes to composer.json in them I managed to install them. But somewhere in that process my event-dispatcher was downgraded to 6.x.  

So now I cannot check the composer why somfony/event-dispatcher to figure out why. I was not aware of that command.

But probably in the process I got updated lock file and allowed composer to downgrade.

What I will do now is to try to switch back to your github repo so I don't need my forks.

This is the output earlier today I hade remaining in terminal output, in case it gives you any info about what had forced it to 7.x.

But seems like it's just some accident that happened for me.

`(main)> composer show symfony/event-dispatcher
name     : symfony/event-dispatcher
descrip. : Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
keywords : 
versions : * v7.0.2
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : https://symfony.com
source   : [git] https://github.com/symfony/event-dispatcher.git 098b62ae81fdd6cbf941f355059f617db28f4f9a
dist     : [zip] https://api.github.com/repos/symfony/event-dispatcher/zipball/098b62ae81fdd6cbf941f355059f617db28f4f9a 098b62ae81fdd6cbf941f355059f617db28f4f9a
path     : /Users/thomasandersson/Documents/GitHub/motoaction_new_generate/vendor/symfony/event-dispatcher
names    : symfony/event-dispatcher, psr/event-dispatcher-implementation, symfony/event-dispatcher-implementation

support
source : https://github.com/symfony/event-dispatcher/tree/v7.0.2

autoload
psr-4
Symfony\Component\EventDispatcher\ => .
exclude-from-classmap

requires
php >=8.2
symfony/event-dispatcher-contracts ^2.5|^3

requires (dev)
psr/log ^1|^2|^3
symfony/config ^6.4|^7.0
symfony/dependency-injection ^6.4|^7.0
symfony/error-handler ^6.4|^7.0
symfony/expression-language ^6.4|^7.0
symfony/http-foundation ^6.4|^7.0
symfony/service-contracts ^2.5|^3
symfony/stopwatch ^6.4|^7.0

provides
psr/event-dispatcher-implementation 1.0
symfony/event-dispatcher-implementation 2.0|3.0

conflicts
symfony/dependency-injection <6.4
symfony/service-contracts <2.5`

**Comment by huangdijia** [comment]
Paste the results of `composer why symfony/event-dispatcher` and let me take a look

**Comment by cyppe** [comment]
Not sure if it's relevant as I managed to lock it to 6.x, and I am not sure how it initially was updated to 7.0.2 

But here it is just in case it gives you any clues:

(main)> composer why symfony/event-dispatcher
moln/php-mysql-replication 1.2.1  requires  symfony/event-dispatcher (^3.1|^4.0|^5.0|^6.0)
symfony/console            v6.4.2 conflicts symfony/event-dispatcher (<5.4)
symfony/http-kernel        v6.4.2 requires  symfony/event-dispatcher (^5.4|^6.0|^7.0)
symfony/mailer             v6.4.2 requires  symfony/event-dispatcher (^5.4|^6.0|^7.0)

Thanks for your support!

**Comment by huangdijia** [comment]
```shell
rm composer.lock vendor
composer install
```
